name: ChrisAkovach
favicon: null
layout_spectrum: 0.6738095858599991
typography_spectrum: 0.48842659895308316
title: Chris Kovach  Animator Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 1
purpose: []
